apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: echo
  annotations:
    backstage.io/kubernetes-id: echo
    backstage.io/kubernetes-namespace: backend
spec:
  type: service
  lifecycle: production
  owner: guest
