apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: echo
  annotations:
    backstage.io/kubernetes-label-selector: "backstage.io/kubernetes-id=echo"
spec:
  type: service
  lifecycle: production
  owner: guests
