apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-applier-role
  namespace: micro
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-rolebinding
  namespace: micro
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: micro
roleRef:
  kind: Role
  name: flux-applier-role
  apiGroup: rbac.authorization.k8s.io
